version: '3.7'
services:
  postgres_mes:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=ViewStore'
    ports:
      - 8276:5432
