version: '3.7'
services:
  timescale:
    image: timescale/timescaledb:latest-pg13
    restart: unless-stopped
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=o'
      - 'POSTGRES_DB=viewstore'
    ports:
      - 5432:5432
